### ISSUE TITLE
Config file for a pipeline

### ISSUE THREAD

**Issue by tr00st** [tr00st/git-stat-tracker#3]
If we've got a string of tools to work together - we should probably have a way of writing a config file to do it in one command. Being able to run `gst run` and have your outputs processed and stored in one go.

First thoughts would be just having a section of `inputs` and a section of `outputs`. By default, all inputs go to all outputs. Look to add some filtering later?

We'd want certain parameters to be specified dynamically, eg:

- Input files for output modules - temp files, or streamed directly internally?
- Commit hash: arg/environment/sniffable?
- Timestamp: current time

Rough concept:

```yaml
inputs:
  lint:
    
outputs:
  db:
    type: dynamodb
    repositoryUri: https://github.com/tr00st/git-stat-tracker
    tableName: git-stat-tracker-stats
```
